platform :ios, '9.0'
use_frameworks!
target 'YOUR_PROJECT' do
    
    pod 'Alamofire'
    pod 'SDWebImage'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'SwiftDate'
    pod 'SwiftyJSON'
    pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Messaging'
    pod 'SwiftKeychainWrapper'
end